import { ReportsDashboardData } from './types';

export const mockReportsData: ReportsDashboardData = {
  questionsPerTeacher: [
    { teacherId: '1', teacherName: 'Dr. Smith', questionCount: 45 },
    { teacherId: '2', teacherName: 'Prof. Johnson', questionCount: 38 },
    { teacherId: '3', teacherName: 'Ms. Williams', questionCount: 52 },
    { teacherId: '4', teacherName: 'Mr. Brown', questionCount: 29 },
    { teacherId: '5', teacherName: 'Dr. Davis', questionCount: 41 },
    { teacherId: '6', teacherName: 'Mrs. Miller', questionCount: 35 },
  ],
  questionsPerSubject: [
    { subjectId: '1', subjectName: 'Mathematics', questionCount: 120 },
    { subjectId: '2', subjectName: 'Physics', questionCount: 85 },
    { subjectId: '3', subjectName: 'Chemistry', questionCount: 95 },
    { subjectId: '4', subjectName: 'Biology', questionCount: 70 },
    { subjectId: '5', subjectName: 'English', questionCount: 65 },
    { subjectId: '6', subjectName: 'History', questionCount: 55 },
  ],
  questionTypeDistribution: [
    { type: 'MultipleChoice', label: 'MCQ', count: 145 },
    { type: 'ShortQuestion', label: 'Short Question', count: 98 },
    { type: 'LongQuestion', label: 'Long Question', count: 67 },
    { type: 'FillInTheBlank', label: 'Fill in the Blank', count: 54 },
    { type: 'TrueFalse', label: 'True False', count: 76 },
  ],
  difficultyDistribution: [
    { difficultyId: '1', difficultyName: 'Easy', count: 120 },
    { difficultyId: '2', difficultyName: 'Medium', count: 180 },
    { difficultyId: '3', difficultyName: 'Hard', count: 140 },
  ],
  recentQuestions: [
    {
      id: '1',
      text: 'What is the derivative of x²?',
      type: 'ShortQuestion',
      subject: 'Mathematics',
      teacher: 'Dr. Smith',
      difficulty: 'Easy',
      createdAt: '2024-01-15T10:30:00Z',
    },
    {
      id: '2',
      text: 'Explain the process of photosynthesis.',
      type: 'LongQuestion',
      subject: 'Biology',
      teacher: 'Ms. Williams',
      difficulty: 'Medium',
      createdAt: '2024-01-15T09:45:00Z',
    },
    {
      id: '3',
      text: 'Which planet is known as the Red Planet?',
      type: 'MultipleChoice',
      subject: 'Physics',
      teacher: 'Prof. Johnson',
      difficulty: 'Easy',
      createdAt: '2024-01-15T08:20:00Z',
    },
    {
      id: '4',
      text: 'The chemical formula for water is ___.',
      type: 'FillInTheBlank',
      subject: 'Chemistry',
      teacher: 'Dr. Davis',
      difficulty: 'Easy',
      createdAt: '2024-01-14T16:15:00Z',
    },
    {
      id: '5',
      text: 'The Battle of Waterloo was fought in 1815.',
      type: 'TrueFalse',
      subject: 'History',
      teacher: 'Mrs. Miller',
      difficulty: 'Medium',
      createdAt: '2024-01-14T14:30:00Z',
    },
  ],
  syncStatus: {
    lastSyncTime: '2024-01-15T11:00:00Z',
    status: 'synced',
    pendingChanges: 0,
  },
};
