export const routePaths = {
  dashboard: '/',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password/:token',
  teachers: '/teachers',
  subjects: '/subjects',
  classes: '/classes',
  chapters: '/chapters',
  difficultyLevels: '/difficulty-levels',
  questionCategories: '/question-categories',
  questions: '/questions',
  papers: '/papers',
  sync: '/sync',
  users: '/users',
  reports: '/reports',
  settings: '/settings',
} as const;
