export const routePaths = {
  dashboard: '/',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password/:token',
  teacherCreate: '/teachers/new',
  teacherEdit: '/teachers/:teacherId/edit',
  questionCreate: '/questions/new',
  questionDetails: '/questions/:questionId',
  questionEdit: '/questions/:questionId/edit',
  subjectCreate: '/subjects/new',
  subjectEdit: '/subjects/:subjectId/edit',
  teachers: '/teachers',
  subjects: '/subjects',
  classes: '/classes',
  chapters: '/chapters',
  difficultyLevels: '/difficulty-levels',
  questionCategories: '/question-categories',
  questions: '/questions',
  papers: '/papers',
  examPaperGenerator: '/papers/generate',
  sync: '/sync',
  users: '/users',
  reports: '/reports',
  settings: '/settings',
} as const;
